server:
  port: 9092

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/hunger_saviour_payments?createDatabaseIfNotExist=true
    username: prapti
    password: prapti21
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}
