server:
  port: 9091

spring:
  application:
    name: RESTAURANT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/restaurants?createDatabaseIfNotExist=true
    username: prapti
    password: prapti21
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


eureka:
  client:
    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}